name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  # ==================================================
  # JOB 1 : UNIT TESTS
  # ==================================================
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest test/test_unit.py -v


  # ==================================================
  # JOB 2 : E2E TESTS
  # ==================================================
  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask application
        run: |
          nohup python app.py > flask.log 2>&1 &

      - name: Wait for application
        run: |
          for i in {1..30}; do
            if curl -f http://127.0.0.1:3000/health; then
              echo "Application is ready"
              exit 0
            fi

            echo "Waiting for application..."
            sleep 1
          done

          echo "Application failed to start"
          cat flask.log
          exit 1

      - name: Run E2E tests
        run: |
          PYTHONPATH=. pytest test/test_e2e.py -v


  # ==================================================
  # JOB 3 : BUILD & PUSH DOCKER HUB
  # ==================================================
  build-and-push:
    name: Build & Push Docker Hub

    # IMPORTANT :
    # Ce job ne démarre que si les deux jobs précédents
    # ont réussi.
    needs:
      - unit-tests
      - e2e-tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build de l'image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/api-final:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/api-final:${{ github.sha }} \
            .

      # Push vers Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-final:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-final:${{ github.sha }}

  deploy:
    name: Deploy Docker container on VM
    needs:
      - unit-tests
      - e2e-tests
      - build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installer sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Déployer sur la VM
        env:
          SSH_PASSWORD: 'Supermotdepasse!42'
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            ubuntu@20.56.74.49 << EOF

            set -e

            echo "Connexion à la VM réussie"

            echo "Connexion à Docker Hub..."
            echo "$DOCKERHUB_PASSWORD" | docker login \
              -u "$DOCKERHUB_USERNAME" \
              --password-stdin

            echo "Récupération de la nouvelle image..."
            docker pull "$DOCKERHUB_USERNAME/api-final:latest"

            echo "Arrêt de l'ancien conteneur..."
            docker stop api-final 2>/dev/null || true

            echo "Suppression de l'ancien conteneur..."
            docker rm api-final 2>/dev/null || true

            echo "Lancement du nouveau conteneur..."
            docker run -d \
              --name api-final \
              --restart unless-stopped \
              -p 49152:3000 \
              "$DOCKERHUB_USERNAME/api-final:latest"

            echo "Conteneur lancé"

            docker ps

          EOF
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

